### PR TITLE
Allow user select of group member address

### PR DESCRIPTION
**Pull request by elv-zenia**
Add hover copy button to Group member address cell and allow user select.

### CODE REVIEW

**Comment by elv-zenia** [comment]
Relates to https://github.com/qluvio/elv-apps-projects/issues/216

**Comment by elv-kevin** [comment]
this looks good, but honestly all that is needed is to remove `user-select: none` from `.table-listing`

**Comment by elv-zenia** [comment]
I'm going to remove the copy button then so this isn't the only table with different functionality.

**Comment by elv-kevin** [comment]
yeah that makes sense, don't need an explicit copy button here.

**Comment by elv-zenia** [comment]
@elv-kevin Updated

**Comment by elv-kevin** [comment]
looks good

**Comment by elv-zenia** [comment]
@elv-kevin can you review the last commit: https://github.com/eluv-io/elv-fabric-browser/pull/96/commits/0495e81e78bdcd3d3a493d08289ab6b9e03f259d? Arun found a bug where manager settings were resetting to false when moving between Members/Managers and Groups tabs.

**Comment by elv-kevin** [comment]
yeah that looks good

**Pull request merged**
