### PR TITLE
Add prev/next buttons to metadata diff

### PR DESCRIPTION
**Pull request by elv-zenia**
Add buttons for scrolling between changes in the object metadata Diff view. Additionally, make the max height of the diff block less than 100% of thew viewport.

Previous button disabled on first change. Next button disabled on last change.

image

https://user-images.githubusercontent.com/91760982/146099292-74b022cd-1b6e-459b-b2ae-044f216ab97d.mov

### CODE REVIEW

**Comment by elv-kevin** [comment]
Looks really good. 

A couple minor requests:
- can you move the buttons to the right side of the panel. As a right handed person it kind of psychologically feels like reaching across my body to get to the buttons on the left
- scrolling directly to the anchor brings it too close to the top. checkout this method for adding a bit of top padding
https://stackoverflow.com/a/56391657

**Comment by elv-zenia** [comment]
@elv-kevin Updated button placement

**Comment by elv-kevin** [comment]
One thing I didn't notice before was that the next button went to the red section, then the green section, separately. It should only go to the top of the first (red) section. The intent is that it's cycling through the diffs, and the entire thing (red + green) is a diff.

Can you also add some minimum height to the loaders involved in the diff section?

**Comment by elv-zenia** [comment]
@elv-kevin Update min height for the loader and changed the handling of a diff. I think it should work considering that the diffs are split into new lines when they're different/back to unchanged.

**Pull request merged**
